# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

In [6]:
# review a document in the establishments collection
pprint(db.establishments.find_one())

{'AddressLine1': 'St Marys Church Of England Primary School',
 'AddressLine2': 'Warren Road',
 'AddressLine3': 'Folkestone',
 'AddressLine4': 'Kent',
 'BusinessName': 'St Marys COE (aided) Primary School',
 'BusinessType': 'School/college/university',
 'BusinessTypeID': 7845,
 'ChangesByServerID': 0,
 'Distance': 4591.871474174837,
 'FHRSID': 289353,
 'LocalAuthorityBusinessID': 'PI/000002468',
 'LocalAuthorityCode': '188',
 'LocalAuthorityEmailAddress': 'foodteam@folkestone-hythe.gov.uk',
 'LocalAuthorityName': 'Folkestone and Hythe',
 'LocalAuthorityWebSite': 'http://www.folkestone-hythe.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'CT19 6QH',
 'RatingDate': '2016-09-13T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': '5',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('641a8b4dcdabda5112bbd583'),
 'geocode': {'latitude': 51.085797, 'longitude': 1.194762},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/289353',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [7]:
# Find the establishments with a hygiene score of 20
query ={'scores.Hygiene': {'$eq': 20}}

# Use count_documents to display the number of documents in the result
hygiene20 = establishments.count_documents(query)
print(hygiene20)
# Display the first document in the results using pprint
pprint(list(establishments.find(query).limit(1)))

41
[{'AddressLine1': '5-6 Southfields Road',
  'AddressLine2': 'Eastbourne',
  'AddressLine3': 'East Sussex',
  'AddressLine4': '',
  'BusinessName': 'The Chase Rest Home',
  'BusinessType': 'Caring Premises',
  'BusinessTypeID': 5,
  'ChangesByServerID': 0,
  'Distance': 4613.888288172291,
  'FHRSID': 110681,
  'LocalAuthorityBusinessID': '4029',
  'LocalAuthorityCode': '102',
  'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
  'LocalAuthorityName': 'Eastbourne',
  'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'BN21 1BU',
  'RatingDate': '2021-09-23T00:00:00',
  'RatingKey': 'fhrs_0_en-gb',
  'RatingValue': '0',
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('641a8b4dcdabda5112bbf0b3'),
  'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}]

In [8]:
# Convert the result to a Pandas DataFrame
results = list(establishments.find(query))
hygiene_df = pd.json_normalize(results)

# Display the number of rows in the DataFrame
print(len(hygiene_df. index) )
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,641a8b4dcdabda5112bbf0b3,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,0.276940,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,641a8b4dcdabda5112bbf434,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,1.278721,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,641a8b4dcdabda5112bbf73f,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,1.159270,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,641a8b4dcdabda5112bbf930,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,0.102020,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,641a8b4dcdabda5112bbf93e,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,0.101446,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,641a8b4dcdabda5112bc02dd,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,0.736349,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,641a8b4dcdabda5112bc0500,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,0.712167,51.535007,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,641a8b4ecdabda5112bc1a2f,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,0.602364,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,641a8b4ecdabda5112bc1e6b,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,0.146450,51.185947,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,641a8b4ecdabda5112bc2687,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,0.462307,51.570050,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [15]:
# Change the data type from String to Int for RatingValue
#establishments.update_many({}, [{'$set': {'RatingValue': {'$toInt': '$RatingValue'}}}])

In [10]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query ={'LocalAuthorityName': {'$regex':'London'},
         'RatingValue': {'$gte': '4'}}

# Use count_documents to display the number of documents in the result
valLondon = establishments.count_documents(query)
print(valLondon)

# Display the first document in the results using pprint
pprint(list(establishments.find(query).limit(1)))

34
[{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
  'AddressLine2': 'Sheppy Kent',
  'AddressLine3': '',
  'AddressLine4': '',
  'BusinessName': "Charlie's",
  'BusinessType': 'Other catering premises',
  'BusinessTypeID': 7841,
  'ChangesByServerID': 0,
  'Distance': 4627.439467780196,
  'FHRSID': 621707,
  'LocalAuthorityBusinessID': 'PI/000025307',
  'LocalAuthorityCode': '508',
  'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
  'LocalAuthorityName': 'City of London Corporation',
  'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'ME12',
  'RatingDate': '2021-10-18T00:00:00',
  'RatingKey': 'fhrs_4_en-gb',
  'RatingValue': '4',
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('641a8b4dcdabda5112bc0ad0'),
  'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}]

In [11]:
# Convert the result to a Pandas DataFrame
results = list(establishments.find(query))
rating_df = pd.json_normalize(results)

# Display the number of rows in the DataFrame
print(len(rating_df. index) )
# Display the first 10 rows of the DataFrame
rating_df.head(10)

34

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,641a8b4dcdabda5112bc0ad0,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,0.508551,51.369321,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,641a8b4dcdabda5112bc0df4,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,0.249256,51.123623,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,641a8b4ecdabda5112bc1941,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,0.561954,51.543831,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,641a8b4ecdabda5112bc2745,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,0.346325,51.464078,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,641a8b4ecdabda5112bc2747,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,0.346337,51.464066,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,641a8b4ecdabda5112bc2e4e,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,0.287555,51.504071,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,641a8b4ecdabda5112bc4f58,1252616,0,PI/000035653,Froottree,Other catering premises,7841,Tereza Joanne King George V Lock,Woolwich Manor Way London,Charlton,...,0.069325,51.501110,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,641a8b4ecdabda5112bc4f5b,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,0.069286,51.501121,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,641a8b4ecdabda5112bc531f,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,0.048006,51.503733,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,641a8b4ecdabda5112bc533c,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of '5', sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [14]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = 51.49014200
longitude = 0.08384000

query ={'geocode.latitude': {'$lte': latitude + degree_search},
        'geocode.latitude': {'$gte': latitude - degree_search},
        'geocode.longitude': {'$lte': longitude + degree_search},
        'geocode.longitude': {'$gte': longitude - degree_search},
        'RatingValue': {'$eq': '5'}
       }
sort =  sort = [('scores.Hygiene', 1)]

# Print the results
pprint(list(establishments.find(query).sort(sort).limit(1)))

[{'AddressLine1': '15 - 21 Old Pier Street',
  'AddressLine2': 'Walton On The Naze',
  'AddressLine3': 'Essex',
  'AddressLine4': '',
  'BusinessName': 'Yates Fish Bar',
  'BusinessType': 'Restaurant/Cafe/Canteen',
  'BusinessTypeID': 1,
  'ChangesByServerID': 0,
  'Distance': 4617.9096191396775,
  'FHRSID': 611936,
  'LocalAuthorityBusinessID': '1545/FOOD',
  'LocalAuthorityCode': '120',
  'LocalAuthorityEmailAddress': 'fhsadmin@tendringdc.gov.uk',
  'LocalAuthorityName': 'Tendring',
  'LocalAuthorityWebSite': 'http://www.tendringdc.gov.uk/',
  'NewRatingPending': False,
  'Phone': '',
  'PostCode': 'CO14 8AH',
  'RatingDate': '2020-02-24T00:00:00',
  'RatingKey': 'fhrs_5_en-gb',
  'RatingValue': '5',
  'RightToReply': '',
  'SchemeType': 'FHRS',
  '_id': ObjectId('641a8b4dcdabda5112bbf420'),
  'geocode': {'latitude': 51.848696, 'longitude': 1.270904},
  'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/611936',
             'rel': 'self'}],
  'meta': {'dataSource': None,
           'extractDate': '0001-01-01T00:00:00',
           'itemCount': 0,
           'pageNumber': 0,
           'pageSize': 0,
           'returncode': None,
           'totalCount': 0,
           'totalPages': 0},
  'scores': {'ConfidenceInManagement': None,
             'Hygiene': None,
             'Structural': None}}]

In [13]:
# Convert result to Pandas DataFrame
results = list(establishments.find(query).sort(sort))
rating_df = pd.json_normalize(results)

# Display the number of rows in the DataFrame
print(len(rating_df. index) )
# Display the first 10 rows of the DataFrame
rating_df.head(10)

10063

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,641a8b4dcdabda5112bbf420,611936,0,1545/FOOD,Yates Fish Bar,Restaurant/Cafe/Canteen,1,15 - 21 Old Pier Street,Walton On The Naze,Essex,...,1.270904,51.848696,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,641a8b4dcdabda5112bbf492,612149,0,2718/FOOD,Walton And Frinton Yacht Club,Restaurant/Cafe/Canteen,1,Walton and Frinton Yacht Club,Mill Lane,Walton On The Naze,...,1.268522,51.851497,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,641a8b4dcdabda5112bbf691,1213083,0,19/00489/CP,Subway,Other catering premises,7841,80 Hamilton Road,Felixstowe,Suffolk,...,1.351780,51.963229,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,641a8b4dcdabda5112bbfb80,667642,0,13/50646/CP,The Mariners,Pub/bar/nightclub,7843,Three Mariners Inn,193 High Road,Trimley St Mary,...,1.313746,51.984696,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,641a8b4dcdabda5112bbfc31,1052994,0,18/00109/FOOD,Warnes Butchers,Distributors/Transporters,7,51 Garland Road,Parkeston,Harwich,...,1.254358,51.942736,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,641a8b4dcdabda5112bbfc38,958510,0,17/00038/FOOD,Hamford View,Restaurant/Cafe/Canteen,1,Hamford View,Clacton Road,Little Oakley,...,1.222682,51.912376,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,641a8b4dcdabda5112bbfd1b,612016,0,1894/FOOD,Balti House,Other catering premises,7841,23 Spring Road,St Osyth,Clacton On Sea,...,1.078133,51.798482,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,641a8b4dcdabda5112bbfd73,1025208,0,17/00124/RESHO,The Lighthouse,Caring Premises,5,Southchurch Avenue,Shoeburyness,Southend-On-Sea,...,0.796968,51.533436,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,641a8b4dcdabda5112bc0271,1080036,0,18/00175/FOOD,Seaview,Takeaway/sandwich shop,7844,32 Station Road,Brightlingsea,Colchester,...,1.022383,51.809921,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,641a8b4dcdabda5112bc08f0,1317234,0,20/00184/RESTUN,Fireaway,Restaurant/Cafe/Canteen,1,376 - 378 London Road,Westcliff-On-Sea,Essex,...,0.695224,51.542328,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [ ]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'scores.Hygiene': {'$eq': 0}}}
# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': "$LocalAuthorityName", 'count': { '$sum': 1 }}
              }
# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': { 'count': -1, '_id': 1 }}
# Print the number of documents in the result

# Print the first 10 results
pipeline = [match_query, group_query, sort_values]
results = list(establishments.aggregate(pipeline))
pprint(results[0:10])

In [ ]:
# Convert the result to a Pandas DataFrame

hygiene_df = pd.json_normalize(results)

# Display the number of rows in the DataFrame
print(len(hygiene_df. index) )
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

In [ ]:
# Create a pipeline that:   'BusinessType': 'Restaurant/Cafe/Canteen',

# 1. Matches establishments with a hygiene score of 0
match_query = {'$match': {'BusinessType': {'$eq': 'Restaurant/Cafe/Canteen'}}}
# 2. Groups the matches by Local Authority
group_query = {'$group': {'_id': "$RatingValue", 'count': { '$sum': 1 }}
              }
# 3. Sorts the matches from highest to lowest
sort_values = {'$sort': { 'count': -1, '_id': 1 }}
# Print the number of documents in the result

# Print the first 10 results
pipeline = [match_query, group_query, sort_values]
results = list(establishments.aggregate(pipeline))
pprint(results[0:10])